Travis 14.04 support: Fix terminal size in tests
test_stbt_control_as_stbt_record_control_recorder_* were failing with:

> EnvironmentError: Unable to print keymap because the terminal is too
> small. Please resize the terminal window.

with Travis Ubuntu 14.04.  Presumably expect was inheriting the TTY size
from somewhere and it's different on Travis's new infrastructure.  This
commit fixes this issue and should also fix the tests failing when run
locally in a small terminal window.