pixel_bounding_box: Return Region of ints, not `numpy.int64`s
When I was working on adding `min_size` to MotionDiff, this caused a
very confusing error in `MotionResult.__bool__`:

    TypeError: __bool__ should return bool, returned numpy.bool_

We were comparing `out_region.width` (numpy.int64) against
`min_size[0]`, and the result was a `numpy.bool_` instead of `bool`.