stbt.get_frame and stbt.save_frame return/operate on OpenCV format
"stbt.get_frame" returns an OpenCV image (i.e. a numpy array) instead of
a GStreamer buffer. The OpenCV image doesn't have any timestamp
information, unlike the GStreamer buffer; but I don't think anyone was
using that timestamp (if you wanted the timestamp you would have been
using "detect_match" or "detect_motion" instead).

"stbt.save_frame" takes an OpenCV image instead of a GStreamer buffer, and
uses the much simpler "cv2.imwrite" to save it to disk.

Note that "stbt.get_frame()" can no longer be used in a boolean context;
stbt-run's "if e.screenshot" would now fail with:

    ValueError: The truth value of an array with more than one element
    is ambiguous. Use a.any() or a.all()