Python3: Don't import from future.moves
For some reason, importing `future/move/__init__.py` tries to import all
other top-level modules immediately. So if you're running `stbt_run.py`
from the source directory it tries to import all other top-level python
files, which fails because `stbt` is only halfway through being imported
itself. For example:

    $ python3 stbt_run.py test.py
    Traceback (most recent call last):
      File "stbt_run.py", line 19, in <module>
        import stbt
      File "stbt/__init__.py", line 33, in <module>
        from _stbt.frameobject import (
      File "_stbt/frameobject.py", line 14, in <module>
        from future.moves.itertools import zip_longest
      File "/usr/lib/python3/dist-packages/future/moves/__init__.py", line 8, in <module>
        import_top_level_modules()
      File "/usr/lib/python3/dist-packages/future/standard_library/__init__.py", line 806, in import_top_level_modules
        with exclude_local_folder_imports(*TOP_LEVEL_MODULES):
      File "/usr/lib/python3/dist-packages/future/standard_library/__init__.py", line 776, in __enter__
        module = __import__(m, level=0)
      File "test.py", line 2, in <module>
        stbt.debug("Hi there")
    AttributeError: module 'stbt' has no attribute 'debug'