Fix `from stbt import *` with Python 2.7
This has been broken since we added Python3 compatibility. Due to `from
__future__ import unicode_literals`, attempting to do `from stbt
import *` fails with:

    TypeError: Item in ``from list'' must be str, not unicode

Of course `__unicode_literals__` must go at the top of the file, so you
can't move it to below `__all__`.

If I add a `b` literal to each element, then Python 3.6 fails with:

    TypeError: Item in stbt.__all__ must be str, not bytes