stbt.conf: Add default configuration values for `stbt batch`
Since the refactoring to Python in #495, `stbt batch run` was failing
with:

> ConfigurationError: No section: 'batch'