Add test_pyramid_roi_too_small: Regression test for opencv error
The error is:

> cv2.error: (-215) _img.size().height <= _templ.size().height &&
> _img.size().width <= _templ.size().width in function matchTemplate

Presumably we are passing a too-small roi into the next pyramid level.
I'll fix this in a future commit.