stbt: Improve error message if Gst 1.0 is unavailable
Recently, I have been using a local built Gstreamer-1.0 using
[jhbuild-gstreamer] in my ubuntu 12.04. And I have encountered below
error.  After debugging for a day, I have find out the cause of error.
When `import gi` was executed, it imported `Gst-0.10.typelib` file in
`/usr/lib/girepository-1.0` directory because there was no
`Gst-1.0.typelib` in the path.  In my environment, `Gst-1.0.typelib` was
located in local home directory because I used [jhbuild-gstreamer].  Of
course, I set my local path to `$GI_TYPELIB_PATH` variable.  But it still
imported `Gst-0.10.typelib`. After copying `Gst-1.0.typelib` file into
`/usr/lib/girepository-1.0`, it worked well.

To find out root cause, I had to start from below error message.  If this
patch had been applied, I would have been able to shorten debugging time.

Error message before applying a patch:

    $./stbt-run --verbose --source-pipeline='v4l2src device=/dev/video0 ! video/x-raw' bat_drone.py
    stbt-run: Arguments:
    control: none
    save_trace: None
    verbose: 1
    args: []
    source_pipeline: v4l2src device=/dev/video0 ! video/x-raw,width=640,height=480
    script: bat_drone.py
    restart_source: False
    structured_logging: None
    sink_pipeline: autovideosink
    save_video:
    FAIL: bat_drone.py: GError: no element "videoconvert"
    Traceback (most recent call last):
      File "./stbt-run", line 70, in <module>
        stbt.get_config('global', 'transformation_pipeline'))
      File "/home/yujin/work/local_repos/stb-tester/stbt/__init__.py", line 1629, in init_run
        save_video, restart_source, transformation_pipeline)
      File "/home/yujin/work/local_repos/stb-tester/stbt/__init__.py", line 1797, in __init__
        self.create_source_pipeline()
      File "/home/yujin/work/local_repos/stb-tester/stbt/__init__.py", line 1841, in create_source_pipeline
        self.source_pipeline_description)
      File "/usr/lib/python2.7/dist-packages/gi/types.py", line 43, in function
        return info.invoke(*args, **kwargs)
    GError: no element "videoconvert"

Error message after applying a patch:

    $ ./stbt-run --verbose --source-pipeline='v4l2src device=/dev/video0 ! video/x-raw,width=640,height=480' bat_drone.py
    Traceback (most recent call last):
      File "./stbt-run", line 14, in <module>
        import stbt
      File "/home/yujin/work/local_repos/stb-tester/stbt/__init__.py", line 32, in <module>
        gi.require_version("Gst", "1.0")
      File "/usr/lib/python2.7/dist-packages/gi/__init__.py", line 52, in require_version
        (namespace, version))
    ValueError: Namespace Gst not available for version 1.0

Fixes #283.

[jhbuild-gstreamer]: https://github.com/joybro/jhbuild-gstreamer