wait_for_motion: Pre-load mask
We were loading it pretty soon afterwards anyway, when initialising the
differ. At this point we don't know how many color channels the differ
wants, but we need to call load_mask so that we can get consistent
debug.

This fixes `test_wait_for_motion_with_region_and_mask` which was failing
like this:

>     debug("Using mask %s" % (mask or "<Image>",))
> ValueError: The truth value of an array with more than one element is
> ambiguous. Use a.any() or a.all()

It also fixes overly verbose debug output when you've passed a numpy
array that you had previously loaded or constructed yourself.