Fix deadlock on GStreamer errors or video loss
This commit partially reverts commit 21ccc2a7, where I introduced the
bug.

It fixes the problem where "stbt run" hangs indefinitely after input
video loss, after printing the following on stderr:

    stbt-run: Attempting to recover from video loss: Stopping source pipeline and waiting 5s...
    stbt-run: Restarting source pipeline...
    stbt-run: Restarted source pipeline
    stbt-run: Attempting to recover from video loss: Stopping source pipeline and waiting 5s...
    stbt-run: Restarting source pipeline...
    stbt-run: Restarted source pipeline
    stbt-run: Attempting to recover from video loss: Stopping source pipeline and waiting 5s...
    stbt-run: Restarting source pipeline...
    stbt-run: Restarted source pipeline
    Traceback (most recent call last):
      File "/mnt/hgfs/youview/stb-tester/stbt.py", line 554, in restart_source_bin
        raise RuntimeError("Too many underruns.")
    RuntimeError: Too many underruns.

restart_source_bin is called from a GObject timeout, so it *is* running
in the GLib MainLoop thread; but it seems that exceptions raised from
the GLib MainLoop event dispatcher aren't propagated up to the caller of
MainLoop.run().