tests: Add test_load_image_twice
In an earlier implementation of the previous commit, I had tried to
modify the alpha channel directly in `_convert_color` but that caused
a bug, caught by `test_that_match_fast_path_is_equivalent`:

> chan[chan < 255] = 0
> ValueError: assignment destination is read-only

Here I'm making the test more explicit, in case the implementation
of `test_that_match_fast_path_is_equivalent` changes.