stbt.py: Check if the source exists before trying to restart it
In the previous commit, the measurements were correctly taken and
everything worked fine, except for the occasional error:

  Traceback (most recent call last):
    File "/usr/local/libexec/stbt/stbt.py", line 1001, in restart_source
      self.source_pipeline.set_state(gst.STATE_NULL)
  AttributeError: 'NoneType' object has no attribute 'set_state'

This is because `Display.restart_source()` is being directly called from
`Display.catchup_live_stream()`. Up until now, restart_source() assumed
that between two of its calls, the source was created again. However, now
that it's directly called from catchup_live_stream, it's possible that the
source still hasn't been created. Therefore, it needs to check if it's
None.