stbt-camera-validate: Remove superflouous utf-8 encoding
`stbt-camera-validate.py` is run via `stbt run`, so since 5af690e calling
`.encode('utf-8')` isn't necessary to write to `sys.stderr`, and was
actually causing a test failure for me in
`test_that_validation_passes_on_pristine_input` among others.  The
backtrace was:

    Traceback (most recent call last):
      File ".../stbt-run", line 83, in <module>
        execfile(args.script)
      File ".../stbt-camera.d/stbt-camera-validate.py", line 243, in <module>
        sys.exit(main(sys.argv))
      File ".../stbt-camera.d/stbt-camera-validate.py", line 239, in main
        failures += validate(c, driver, validate_match=not args.positions_only)
      File ".../stbt-camera.d/stbt-camera-validate.py", line 153, in validate
        .encode('utf-8'))
      File "/usr/lib/python2.7/codecs.py", line 351, in write
        data, consumed = self.encode(object, self.errors)
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 5: ordinal not in range(128)