stbt.Display.on_error: Print debug info for HDPVR error
...when rebooting the system under test (issue #139).

With the resulting information I'll be able to write an `if` statement
to handle this particular error from the HDPVR.

The error is:

    Device '/dev/video0' does not support video capture
    gstv4l2object.c(2401): gst_v4l2_object_set_format ():
    /GstPipeline:pipeline2/GstV4l2Src:v4l2src1:
    Call to G_FMT failed: (Bad address)

Searching for the above error message in the gst-plugins-good source
code reveals that it is only raised from one
place (gst_v4l2_object_set_format), with domain=RESOURCE and
code=SETTINGS.