stbt.get_frame, press, etc: Improve error message if called without stbt-run
These functions don't work without video-capture & infrared hardware,
which is configured by `stbt run`. If you just `import stbt` and run it
with `python` it doesn't work.

Previously you'd get:

    AttributeError: 'NoneType' object has no attribute 'get_frame'

Now you get:

    RuntimeError: stbt.get_frame isn't configured to run on your hardware