stbt.get_frame: Improve error message if video-capture uninitialised
If you are importing `stbt` as a library and you try to call
`stbt.get_frame()` without initialising the video-capture
pipeline (which is normally done by `stbt run`), you'd get the following
exception:

> AttributeError: 'NoneType' object has no attribute 'get_frame'

This also happens if you're running `stbt auto-selftest` on your page
objects, and you have forgotten to pass `self._frame` explicitly into
any image-processing calls like `stbt.match`.