_stbt/libstbt.py: Make it pyright clean
> error: Too few type arguments provided for "ndarray"; expected 2 but
> received 1

ndarray takes a shape type as well as dtype type.

    >>> print(NDArray[numpy.uint8])
    numpy.ndarray[typing.Any, numpy.dtype[numpy.uint8]]

`numpy.typing.NDArray` was added in 1.21 (Ubuntu 22.04 has 1.21.5).