Travis 14.04 support: Tests: Use C.UTF-8 locale rather than en_GB.utf8
Otherwise `test_stbt_batch_printing_unicode_characters_in_scripts` fails
with:

> UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in
> position 1: ordinal not in range(128)

because the `en_GB.utf8` locale is not available. on the new Travis
infrastructure.  `C.UTF-8` should be available everywhere.