press_and_wait: Fix regression
Since 75fd9feb65d `press_and_wait` has failed with the exception:

    Traceback (most recent call last):
      ...
      File "test.py", line 7, in <module>
        assert stbt.press_and_wait("white")
      File "_stbt/transition.py", line 82, in press_and_wait
        press_result = _dut.press(key)
    AttributeError: 'NoneType' object has no attribute 'press'

This wasn't caught by our existing tests because each of them inject a
custom `dut` for testing and this issue was caused by not defaulting `dut`
correctly.