stbt.match: Fix coordinates of match at smaller pyramid levels
In commit 0a4e6a1dc249 (stbt.match: Pyramid optimisation: Ignore pixels
on edge of reference image) we ignore 1px border of the template (and
its transparency mask) at smaller pyramid levels. See that commit
message for the motivation.

That introduced a regression:

* Conditions: the smaller (cropped) template matched right at the edge
  of the frame, but not at the position 1 pixel removed from the
  edge (note that this means the *uncropped* template won't match
  anywhere in the frame, because it can't match at a position where part
  of the template is outside of the frame). The correct behaviour under
  these conditions is to return "no match".

* Actual behaviour: `cv2.matchTemplate` printed the following error:

  > cv2.error: (-215) _img.size().height <= _templ.size().height &&
  > _img.size().width <= _templ.size().width in function matchTemplate

* Cause: The roi (region of interest) from the previous pyramid level's
  heatmap is well outside of the actual frame at the larger level. This
  is because the heatmap size increases as the template decreases. Then
  when we give this roi (partly outside the frame) to
  `cv2.matchTemplate`, opencv crops it to the boundaries of the frame,
  and we end up with a roi smaller than the template.

This fixes the regression test `test_pyramid_roi_too_small` added in a
previous commit to debug this issue.

Notes:

* In 0a4e6a1dc249 we did `roi = roi.extend(x=-1, y=-1)` because the
  previous level's `matchTemplate` was telling us:

        the position within the frame (origin 0,0) of the template's
        pixel (1,1)

  Now `matchTemplate` is telling us:

        the position within the frame (origin 1,1) of the template's
        pixel (1,1)

  ...which is the same as:

        the position within the frame (origin 0,0) of the template's
        pixel (0,0)

  ...so we can remove `roi.extend(-1, -1)`.

* In an earlier version of this commit I was cropping the bottom & right
  edges of the frame too: `downsampled = downsampled[1:-1, 1:-1]`
  instead of:             `downsampled = downsampled[1:,   1:]`.

  This meant that an odd-sized template wouldn't match an even-sized
  frame if the template & frame had features (edges) on the right/bottom
  edge of the frame, because `pyrDown` can lose features at the bottom
  and/or right of an image if it is even-shaped, but not if it's
  odd-shaped.

  Why: pyrDown rounds the size up so if you start with a 41x41 image you
  get 21x21, not 20x20.
  pyrDown blurs and then discards odd-numbered columns & rows (where the
  first column/row is 0, so the left & top column/row are always kept).
  Therefore: features (edges) at the right of the image will be kept if
  the image was odd-sized, but can be lost if it was even-sized.

  It's ok to discard some information from the template (because you'll
  still find the rest of the template, and then at the larger pyramid
  level you'll search again with the original template) but if you
  discard that information from the frame (and not from the template)
  then you won't find the template in the frame.

  Note that "on the edge of the frame" doesn't have necessarily mean the
  edge of the full 720p frame, if the user passed a region to
  `stbt.match`.